### ISSUE TITLE
can I use this as a mobile app restful service?

### ISSUE THREAD

**Issue by markzhong88** [obijywk/neural-style-server#5]
Hi, thank you for the server setup, I wonder if I want to handle mobile app photo transfer, how can I modify this to fit a restful service?

Also is it hard to port this to flask?

**Comment by obijywk** [comment]
Yeah, you could simply ignore the existence of the Polymer client, and call the Node.js server directly from a mobile app. Right now the results are only returned via the /updates websocket, though, which isn't exactly RESTful - you might want to add a new route for fetching render status that's a normal HTTP call instead of a websocket.

Re-implementing the server in Flask also seems doable, the server isn't actually doing very much.

I'm closing this issue, though, because it's not really a specific feature request. Adding a non-websocket route for returning render status could be an issue opened here. But disabling/removing the Polymer client or porting to Flask isn't going to happen in this repo.
